# 安装目录 

software_dir: '/data/software'
# /data/software/image
#/data/software/bin
#/data/software/rpm
#/data/software/ssl

k8s_work_dir: '/opt/kubernetes'
etcd_work_dir: '/opt/etcd'
tmp_dir: '/tmp/k8s'
data_k8s_dir: '/data/k8s-node'
docker_data_dir: '/data/docker'

# 集群网络
service_cidr: '10.0.0.0/24'
server_csr_dns: '10.0.0.1'
cluster_dns: '10.0.0.10'   # 与roles/addons/files/coredns.yaml中IP一致，并且是service_cidr中的IP
pod_cidr: '172.16.0.0/16' # 与roles/addons/files/calico.yaml中网段一致
service_nodeport_range: '30000-32767'
cluster_domain: 'cluster.local'

# 高可用，如果部署单Master，该项忽略
vip: '192.168.129.31'
nic: 'ens33'  # 修改为实际内网网卡名

# 自签证书可信任IP列表，为方便扩展，可添加多个预留IP
cert_hosts:
  # 包含所有LB、VIP、Master IP和service_cidr的第一个IP
  k8s:
    - 10.0.0.1
    - 192.168.129.31
    - 192.168.129.32
    - 192.168.129.33
    - 192.168.129.34
  # 包含所有etcd节点IP
  etcd:
    - 192.168.129.31
    - 192.168.129.32
    - 192.168.129.33

coredns_image: 'registry.aliyuncs.com/google_containers/coredns:1.6.5'

flannel_cni_image: 'rancher/mirrored-flannelcni-flannel:v0.19.0'
flannel_cni_plugin_image: 'rancher/mirrored-flannelcni-flannel-cni-plugin:v1.1.0'