---
- name: 创建工作目录
  file: dest={{ etcd_work_dir }}/{{ item }} state=directory
  with_items:
    - bin
    - cfg
    - ssl
    - data

- name: 分发并解压etcd二进制包
  copy: src={{software_dir}}/bin/{{ item }} dest={{ etcd_work_dir }}/bin mode=0755
  with_items:
  - etcd
  - etcdctl


- name: 分发证书
  copy: src={{software_dir}}/ssl/etcd/{{ item }} dest={{ etcd_work_dir }}/ssl
  with_items:
    - ca.pem
    - ca-key.pem
    - server.pem
    - server-key.pem

- name: 分发etcd配置文件
  template: src=etcd.conf.j2 dest={{ etcd_work_dir }}/cfg/etcd.conf

- name: 分发service文件
  template: src=etcd.service.j2 dest=/usr/lib/systemd/system/etcd.service
    
- name: 启动etcd
  systemd: name=etcd state=restarted enabled=yes daemon_reload=yes

- name: 分发etcd脚本
  template: src=etcd.sh.j2 dest={{ etcd_work_dir }}/etcd.sh mode=u+x

- name: 获取etcd集群状态
  shell: /bin/bash {{ etcd_work_dir }}/etcd.sh
  register: status 
- debug: var=status.stdout_lines
